figure;
plot(x_test,y_predict_1a,'*',x_test,y_predict_1b,'*',x_test,y_predict_1c,'*',x_test,y_predict_1d,'*',...
     x_test,y_predict_1e,'*',x_test,y_predict_1f,'*',x_test,y_predict_1g,'*',x_test,y_predict_1h,'*',...
     x_train,y_train,'k+',x_test,y_test,'ko');